# Generated by Django 5.1.1 on 2024-10-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=255)),
                ('admin_last_name', models.CharField(blank=True, max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallPackageModel',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_price', models.FloatField()),
                ('total_coins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(default='unknown', max_length=100)),
                ('customer_email', models.EmailField(default='unknown', max_length=254)),
                ('customer_phone_number', models.CharField(max_length=50)),
                ('customer_password', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Normal User', 'Normal User'), ('Agent User', 'Agent User')], default='Normal User', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTransactionModel',
            fields=[
                ('agent_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_rabit_app.customermodel')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='my_rabit_app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('razorpay_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_signature', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_rabit_app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserPurchaseModel',
            fields=[
                ('user_purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_rabit_app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_coins', models.IntegerField(default=300, null=True)),
                ('call_amount', models.FloatField(default=0.0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_rabit_app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalHistoryModel',
            fields=[
                ('agent_purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawal_amount', models.FloatField()),
                ('withdrawal_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_rabit_app.customermodel')),
            ],
        ),
    ]
