# Generated by Django 5.1.1 on 2024-10-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0002_customermodel_rating_customermodel_terms_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='adhaar_no',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_id', to='my_rabit_app.customermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='my_rabit_app.customermodel')),
            ],
        ),
    ]
