# Generated by Django 5.1.1 on 2024-11-22 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0003_remove_customermodel_rating_customermodel_adhaar_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailsModel',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('agora_channel_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='my_rabit_app.customermodel')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='my_rabit_app.customermodel')),
            ],
        ),
    ]
