# Generated by Django 5.1.1 on 2024-11-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0004_calldetailsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='razorpay_payment_signature',
        ),
    ]
