# Generated by Django 5.1.1 on 2024-11-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0005_remove_paymentmodel_razorpay_payment_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalHistoryModel',
        ),
    ]
