# Generated by Django 5.1.1 on 2024-11-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0006_delete_withdrawalhistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalHistoryModel',
            fields=[
                ('agentpurchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawal_amount', models.FloatField()),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('withdrawal_method', models.CharField(choices=[('g pay', 'G Pay'), ('phone pay', 'Phone Pe'), ('bank', 'Bank Transfer')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='my_rabit_app.customermodel')),
            ],
        ),
    ]
