# Generated by Django 5.1.1 on 2024-12-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_rabit_app', '0007_withdrawalhistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='is_engaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
    ]
